# Generated by Django 4.2.9 on 2024-01-07 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Blog",
        ),
    ]
