# Generated by Django 4.2.9 on 2024-01-07 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_post_blog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="Post",
        ),
    ]
