# Generated by Django 4.1.13 on 2023-12-22 04:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=ckeditor.fields.RichTextField(default="No Comment..."),
        ),
    ]
