# Generated by Django 4.1.13 on 2023-12-22 05:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_comment_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="about",
            field=ckeditor.fields.RichTextField(default="No About..."),
        ),
    ]
