# Generated by Django 4.1.13 on 2023-12-22 21:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_profile_bio_profile_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="no_picture.png"
            ),
        ),
    ]
