# Generated by Django 4.2.7 on 2023-11-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_alter_sale_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csv",
            name="activated",
        ),
        migrations.AddField(
            model_name="csv",
            name="csv_file",
            field=models.FileField(null=True, upload_to="csvs"),
        ),
        migrations.AlterField(
            model_name="csv",
            name="file_name",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
