(function(g){var window=this;'use strict';var R2=function(a){a.publish("cardstatechange",a.Dl()&&a.Up()?1:0)},S2=function(a,b){var c=g.Ra(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},feb=function(a){var b=g.Cm(a);
a=g.Fm(a);return new g.qm(b.x,b.y,a.width,a.height)},geb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.Ps(a,b,function(){g.Qs(e);c.apply(a,arguments)},d)},V2=function(a){delete T2[g.Va(a)];
g.Gg(T2)&&U2&&U2.stop()},ieb=function(){U2||(U2=new g.sp(function(){heb()},20));
var a=U2;a.isActive()||a.start()},heb=function(){var a=g.Ya();
g.wg(T2,function(b){jeb(b,a)});
g.Gg(T2)||ieb()},W2=function(a,b,c,d){g.Fp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},jeb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;keb(a,a.progress);a.progress==1?(a.j=0,V2(a),a.onFinish(),a.Ks()):a.isPlaying()&&a.pO()},keb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},leb=function(a,b){g.Nh.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},X2=function(a,b,c,d,e){W2.call(this,b,c,d,e);
this.element=a},meb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
X2.call(this,a,b,c,d,e)},neb=function(a){return Math.pow(a,3)},oeb=function(a){return 3*a*a-2*a*a*a},peb=function(a){g.O.call(this);
this.B=a||window;this.j=[]},Y2=function(a){return a.baseUrl||null},Z2=function(a,b){return g.pn(g.El(a,b),function(c){return!!c})},qeb=function(a,b,c){function d(oa){var Y=oa.hovercardButton;
if(!Y)return null;Y=Y.subscribeButtonRenderer;if(!Y)return null;var R=f(Y.unsubscribedButtonText),T=f(Y.subscribedButtonText);if(Y.subscribed){var v=f(Y.subscriberCountWithUnsubscribeText);var W=f(Y.subscriberCountText)}else v=f(Y.subscriberCountText),W=f(Y.subscriberCountWithSubscribeText);var bb=null;if(oa.signinEndpoint){bb=S2(oa,"signinEndpoint","webNavigationEndpointData","url");if(!bb){var ub,ob;bb=(ob=g.Q((ub=Y.signInEndpoint)==null?void 0:ub.commandMetadata,g.K1))==null?void 0:ob.url}if(!bb)return null}return R&&
(T||bb)?{subscribed:Y.subscribed,subscribeText:R,subscribeCount:v,unsubscribeText:T,unsubscribeCount:W,enabled:Y.enabled,signinUrl:bb,classic:oa.useClassicSubscribeButton}:null}
function e(oa){if(oa){var Y=[],R=oa.videoId;R&&Y.push("v="+R);(R=oa.playlistId)&&Y.push("list="+R);(oa=oa.startTimeSeconds)&&Y.push("t="+oa);return"/watch?"+Y.join("&")}}
function f(oa){if(!oa)return null;var Y=oa.simpleText;return Y?Y:oa.runs?g.El(oa.runs,function(R){return R.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,y=!1,A=null,C=null,G=null,H=null,M=null,N=null;if(h==="VIDEO")g.Q(l,g.iy)?m=g.Q(l,g.iy).url:(N=g.Q(l,g.bR),m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.Q(l,g.iy)?m=g.Q(l,g.iy).url:(N=g.Q(l,g.bR),m=e(N)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(y=S2(l,"browseEndpoint","browseId"))u=y,m="/channel/"+u;n=!1;q="new";(y=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((G=S2(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=S2(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=S2(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:
null,V="";if(b.metadata){var ea=f(b.metadata);ea&&(V=ea)}return{id:"element-"+c,type:h,title:f(b.title),metadata:V,callToAction:f(b.callToAction),mY:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,pG:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:y,targetUrl:m||null,K$:n,sessionData:X?{itct:X}:null,pfa:q,EE:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:Z2(b.impressionUrls||[],Y2),A$:Z2(b.hovercardShowUrls||[],Y2),clickUrls:Z2(l.loggingUrls||[],Y2),visualElement:g.Tw(b.trackingParams),productPrice:H,additionalFeesText:M,watchEndpoint:N||null}},reb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:Z2(a.impressionUrls||[],Y2),elements:Z2(a.elements||[],function(d,e){return qeb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Tw(a.trackingParams));return c},seb=function(a){g.gY.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.W=!0;this.K=0;a=a.U();this.Z=g.BP(a)||g.DP(a);this.events=new g.aG(this);g.P(this,this.events);this.events.T(this.player,g.DE("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.EE("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.kc);this.events.T(window,"focus",this.qda);this.load();var b=g.eh("STYLE");(g.Wg("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.jh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},teb=function(a){return a.player.getVideoData().Jf?"current":a.Z?"new":"current"},$2=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},ueb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=reb(f,teb(a))));a3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Mw;d&&(c.postParams={ad_tracking:d});if(b=g.bMa(b))if(b=g.Lf(b),b=g.Hf(b))a.C=g.Sr(b,c)},a3=function(a,b,c){c=c===void 0?!0:c;
a.player.kf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.w(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.N.length>0&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&veb(a);c=[];d=new g.BE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.S({I:"div",S:"ytp-ce-shadow"}),g.SS(a.player,a.B.element,4),a.D=new g.By(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=web(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.SS(a.player,f.element,4);var h=new g.BE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);xeb(a,f,e)}else g.ex(new g.mt("buildEndscreenElement null",
e))}a.player.qf(c);a.kc()}},veb=function(a){var b=g.Vw(),c=g.Ww();
c&&b&&a.endscreen.visualElement&&g.rr(g.qx)(void 0,c,b,a.endscreen.visualElement)},web=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.EE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:b3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:c3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Jp(b.title||"")},va:b.title},{I:"div",S:b.pG?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
va:b.videoDuration||void 0}]}]};c=new g.S(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.EE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:b3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:c3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Jp(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.S(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.EE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],X:{href:c3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Jp(b.title||"")},va:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:b3(b)}]};c=new g.S(c);var d=g.Xg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Ap(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.NY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.EE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.Jp(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-website-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],X:{href:c3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:b3(b)},{I:"div",S:"ytp-ce-expanding-icon",X:yeb(b.iconUrl)}]};c=new g.S(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.EE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.Jp(b.title||"")},va:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:c3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:b3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
va:b.callToAction||void 0}]}]},c=new g.S(a)}b.isPlaceholder&&g.Ap(c.element,"ytp-ce-placeholder");return c},b3=function(a){if(a.mY)var b=a.mY.thumbnails;
return yeb(b?b[b.length-1].url:null)},yeb=function(a){return a?{style:"background-image: url("+a+")"}:{}},xeb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.W&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.Ap(b.element,"ytp-ce-force-expand"),d3(a,c.id,!0)):(g.Cp(b.element,"ytp-ce-force-expand"),g.Cp(b.element,"ytp-ce-element-hover"),d3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){zeb(a,b,c)});
b.listen("mouseleave",function(){Aeb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.Ap(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Beb(a,c,m)});
b.listen("keypress",function(m){Beb(a,c,m)});
b.listen("focus",function(){zeb(a,b,c)});
b.listen("blur",function(){Aeb(a,b,c)});
b.listen("touchstart",function(){zeb(a,b,c)});
var l=g.Zg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Cp(b.element,"ytp-ce-element-hover");g.Cp(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.W=m.keyCode===9&&!m.shiftKey});
d(g.Zg("ytp-sb-subscribe",b.element));d(g.Zg("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Beb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.zp(d,"ytp-ce-element");){g.zp(d,"subscribe-label")&&Ceb(a,b);
if(g.zp(d,"ytp-ce-channel-subscribe"))return;d=d.parentElement||null}if(!d||g.zp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Aeb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.pfa==="new")Ceb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Lf(c3(a,b.targetUrl)),c=g.Hf(c),g.pz(c,void 0,b.sessionData);else{var e=g.QP(a.player.U())||a.player.getVideoData().Jf,f=function(){var h=c3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=
g.xr(h);e&&n&&(n.v||n.list)?a.player.Gp(n.v,l,n.list,!1,void 0,m||void 0):g.oz(h,l)};
Ceb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},c3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.YP(a)+b}else return"";return b},zeb=function(a,b,c){g.zp(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.Ap(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.sp(function(){g.Ap(b.element,"ytp-ce-element-hover")},200)).start():g.Ap(b.element,"ytp-ce-element-hover"),e3(a,c.A$),d3(a,c.id,!0))},Aeb=function(a,b,c){g.Cp(b.element,"ytp-ce-element-hover");
g.Cp(b.element,"ytp-ce-force-expand");d3(a,c.id,!1)},d3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.w(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Ep(a.j[e].element,"ytp-ce-element-shadow-show",c)},e3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||$2(a))c&&c();else{b=Deb(a,b);var e=0,f=!1,h=new g.sp(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.nv(b[a],d)}},Ceb=function(a,b,c){e3(a,b.clickUrls,c);
(a=g.Ww())&&b.K$&&g.Bx(a,b.visualElement)},Deb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Eeb(b[d],c));return a},Eeb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Feb=function(a){return typeof a==="string"?a:""},f3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Geb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},g3=function(a){return a.value?a.value:null},h3=function(a){if(!a)return null;
var b=g.Lf(Feb(a.value));b=g.Hf(b);if(!b)return null;var c=f3(a.target,Heb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new Geb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},Ieb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Leb=function(a){if(!a)return null;
var b=f3(a.type,Jeb),c=f3(a.trigger,Keb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=h3(a?a:null);return b?new Ieb(b,c,a):null},Meb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Neb=function(a,b){return g.Tb(a.action,b)},Oeb=function(a,b){this.context=a;
this.j=b},Peb=function(a){return a.customMessage?i3("div","iv-card-message",a.customMessage):""},j3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},Qeb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.w(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(i3("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},i3=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Jp(c);return{I:a,X:b,va:c}},Reb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.SE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.SE+");");c.dir=g.Jp(a.customMessage);var d=[{I:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,X:c,V:d}},k3=function(a,b,c,d){if(d){b=g.w(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.wj.click,5)}},Seb=function(a,b){this.merchant=a;
this.price=b},Teb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},Ueb=function(a,b){return b?b:Teb(a)?"current":"new"},l3=function(a,b){g.O.call(this);
var c=this;this.element=a;this.context=b;this.kb=!1;this.Ta=new Map;this.Xa=new Map;this.context.J.addEventListener(g.DE("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.EE("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)})},m3=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.KN(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.kb=!1});
a.context.j.listen(b,"touchmove",function(){a.kb=!0})},Veb=function(a){var b;
return((b=g.Q(a,g.iy))==null?0:b.url)?g.Q(a,g.iy).url:(a=g.Q(a,g.bR))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},n3=function(a,b,c){return{NZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
l3:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
mN:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Web=function(a,b,c){l3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ab=this.La=this.Gb=this.C=this.isInitialized=!1;this.cards=[];this.rb=this.Z=this.Ja=this.G=this.Ua=this.j=null;this.oa=[];this.qa=this.N=this.Gf=this.Fa=null;this.K=0;this.Ca=new g.sp(function(){},c.Y.jk?4E3:3E3);
g.P(this,this.Ca);this.ib=new g.sp(function(){});
g.P(this,this.ib);this.Aa=new Oeb(c,function(e,f,h,l,m,n){m3(d,e,f,h,l,m,n)});
this.W=new g.S({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.P(this,this.W);this.D=this.W.element;this.Va=new g.By(this.W,330);g.P(this,this.Va);this.Kb=g.Zg("iv-drawer-header-text",this.D);this.B=g.Zg("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Gb&&o3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Gb=d.C)&&p3(d)});
this.Oa=new g.aG(this);g.P(this,this.Oa);this.J.addEventListener("videodatachange",this.Bu.bind(this))},Xeb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){o3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){p3(a)});
var c=b.headerText;g.lh(a.Kb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.Tw(b.trackingParams);a.N=g.Tw(b.closeTrackingParams);a.Gf=g.Tw(b.iconTrackingParams)},Yeb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.bb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.Px(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,wj:{},Xp:null,gk:e.trackingParams?g.Tw(e.trackingParams):null,Gf:f&&f.trackingParams?g.Tw(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
SE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};q3(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.Px(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:r3(a,c,b,f),sponsored:!1,wj:n3(f,e,f.command),Xp:f.trackingParams?g.Tw(f.trackingParams):null,gk:e.trackingParams?g.Tw(e.trackingParams):null,Gf:l&&l.trackingParams?g.Tw(l.trackingParams):null,imageUrl:s3(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.Px(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,SE:null,title:f.title?g.Px(f.title):"",customMessage:f.callToAction?g.Px(f.callToAction):"",url:g.Q(f.command,g.iy).url?h3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.iy).url}):null,onClickCommand:null};q3(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.Px(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:r3(a,c,b,e),sponsored:!1,wj:n3(e,f,e.endpoint),Xp:e.trackingParams?g.Tw(e.trackingParams):null,gk:f.trackingParams?g.Tw(f.trackingParams):null,Gf:l&&l.trackingParams?g.Tw(l.trackingParams):null,channelId:g.Q(e.endpoint,g.vR).browseId,customMessage:e.customText?g.Px(e.customText):null,profileImageUrl:s3(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.Px(e.channelName):"",metaInfo:[e.subscriberCountText?g.Px(e.subscriberCountText):""],url:h3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.vR).canonicalBaseUrl?g.Q(e.endpoint,g.vR).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.vR).browseId}),onClickCommand:null};q3(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.Px(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:r3(a,c,b,e),sponsored:!1,wj:n3(e,f,e.action),Xp:e.trackingParams?g.Tw(e.trackingParams):null,gk:f.trackingParams?g.Tw(f.trackingParams):null,Gf:l&&l.trackingParams?g.Tw(l.trackingParams):null,vI:s3(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.Px(e.customMessage):null,playlistVideoCount:g.Px(e.playlistVideoCount),title:e.playlistTitle?g.Px(e.playlistTitle):"",metaInfo:[e.channelName?g.Px(e.channelName):
"",e.videoCountText?g.Px(e.videoCountText):""],url:h3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Veb(e.action)}),onClickCommand:null};q3(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.Px(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:r3(a,c,b,e),sponsored:!1,wj:n3(e,f,e.action),Xp:e.trackingParams?g.Tw(e.trackingParams):null,gk:f.trackingParams?g.Tw(f.trackingParams):null,Gf:l&&l.trackingParams?g.Tw(l.trackingParams):null,vI:s3(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.Px(e.lengthString):null,customMessage:e.customMessage?g.Px(e.customMessage):null,title:e.videoTitle?g.Px(e.videoTitle):"",metaInfo:[e.channelName?g.Px(e.channelName):
"",e.viewCountText?g.Px(e.viewCountText):""],isLiveNow:!!e.badge,url:h3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Veb(e.action)}),onClickCommand:null};q3(a,b)}}}}}a.K++},s3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},r3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},$eb=function(a,b){if(b=Zeb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Bf.id),g.jh(b.WO),g.Xb(a.cards,b),a.BJ(),t3(a)},o3=function(a,b,c){if(!a.C){a.Va.show();
a.Ua=new g.sp(function(){g.Ap(a.context.J.getRootNode(),g.S_.IV_DRAWER_OPEN)},0);
a.Ua.start();a.Oa.T(a.B,"mousewheel",function(h){a.Ca.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.Ww();d&&a.Fa&&a.N&&g.zx(d,[a.Fa,a.N]);b={TRIGGER_TYPE:b};for(var e=g.w(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.P_||(f.P_=!0,afb(a.context.logger,f.Bf.wj.NZ,b)),d&&g.zx(d,[f.Bf.Xp]);R2(a.J);c&&(a.G=new g.sp(function(){a.Ja=a.Z;a.rb.focus()},330),a.G.start())}},p3=function(a){a.C&&(a.Va.hide(),g.Ws(a.Oa),g.Cp(a.context.J.getRootNode(),g.S_.IV_DRAWER_OPEN),a.C=!1,R2(a.J),a.G&&a.G.stop(),a.G=new g.sp(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.G.start())},bfb=function(a){g.Bp(a.Ib(),
[g.S_.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.SS(a.J,a.D,5);a.nJ();a.Z=g.Zg("ytp-cards-button",a.J.getRootNode());a.rb=g.Zg("iv-drawer-close-button",a.D);a.isInitialized=!0},cfb=function(a){a.oa.push(g.Gv("iv-teaser-shown",a.b5,a));
a.oa.push(g.Gv("iv-teaser-hidden",a.haa,a));a.oa.push(g.Gv("iv-teaser-clicked",a.a5,a));a.Ab=!0},dfb=function(a,b){var c;
return b.onClickCommand&&((c=g.Q(b.onClickCommand,g.Rbb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.qa=b,!0):!1},efb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.tQ(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.Q(h[0],g.F3a))==null?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},q3=function(a,b){if(!dfb(a,b)||efb(a,b)){var c=ffb(a,b);
if(c){var d={Bf:b,WO:c.element,P_:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Ab||cfb(a),$eb(a,b.id),c=a.findLastIndex(d),g.cc(a.cards,c,0,d));else{a.isInitialized||bfb(a);$eb(a,b.id);var e=a.findLastIndex(d);g.cc(a.cards,e,0,d);c.Ha(a.B,e);a.BJ()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,t3(a),gfb(a,d),o3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&hfb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){hfb(a,d)}),t3(a))}}},ffb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",va:b.displayDomain}:void 0;var d=Reb(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?g3(b.url)||"":""},V:[j3(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[i3("h2",void 0,b.title),d]}]}]};c=new g.S(c);k3(a,g.Yg("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],X:{href:g3(b.url)||"","data-ytid":b.channelId},V:[j3(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Peb(b),{I:"h2",S:"iv-card-primary-link",va:b.title},Qeb(b)]}]}]};c=new g.S(c);k3(a,g.Yg("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:g3(b.url)||""},V:[j3(b.vI,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Peb(b),i3("h2","iv-card-primary-link",b.title),Qeb(b)]}]}]};
c=new g.S(c);k3(a,g.Yg("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=b.offers.length!=0;c=["iv-card"];d="";var f=Reb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",va:f.merchant}),f={I:"div",V:e});e=b.url?g3(b.url)||"":"";c={I:"div",Ka:c,X:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",va:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[i3("h2",d,b.title),f]}]}]};c=new g.S(c);d=g.eh("span");g.lh(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Dd(d,"adInfo");k3(a,g.Yg("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",va:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:((c=b.url)==null?void 0:g3(c))||""},V:[j3(b.vI,d),{I:"div",S:"iv-card-content",V:[Peb(b),i3("h2","iv-card-primary-link",b.title),Qeb(b),f]}]}]};c=new g.S(e);k3(a,g.Yg("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},ifb=function(a){if(a.j)return a.j.Bf.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.Fl(a.cards,function(c){return c.Bf.type==="productListing"})}return g.Fl(a.cards,function(c){return c.Bf.type==="productListing"})},t3=function(a){g.Ep(a.J.getRootNode(),"ytp-cards-shopping-active",ifb(a))},hfb=function(a,b){if(!g.zp(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Ww(),d=a.j?a.j.Bf.Gf:a.Gf;
c&&d&&g.Ax(c,[d]);a.j=b;t3(a)}(c=a.isInitialized&&a.Ib().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.Bf.teaserDurationMs&&a.J.GC(!0,{teaserText:b.Bf.teaserText,durationMs:b.Bf.teaserDurationMs,onClickCommand:b.Bf.onClickCommand});a.ib.isActive()||((!a.C||!a.Ca.isActive()&&a.La)&&gfb(a,b),a.ib.start(910+b.Bf.teaserDurationMs))}},gfb=function(a,b){a.W.Eb?(b=new W2([0,
a.B.scrollTop],[0,b.WO.offsetTop],600,oeb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.Lx(a.W,!0),a.B.scrollTop=b.WO.offsetTop,g.Lx(a.W,!1))},u3=function(a){return a.j&&a.j.Bf?a.j.Bf:a.cards[0]&&a.cards[0].Bf?a.cards[0].Bf:null},Zeb=function(a,b){return g.Tb(a.cards,function(c){return c.Bf.id===b})},v3=function(a,b,c){l3.call(this,a,b);
this.annotation=c;this.isActive=!1},jfb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(Number(b.start_ms),Number(b.end_ms),a.annotation.id,function(){a.show()},function(){a.hide()})},w3=function(a,b,c){v3.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},kfb=function(a,b){var c=c===void 0?0:c;
var d=feb(b).width;g.Am(b,d);c=new meb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,neb);g.P(a,c);a.context.C.listen(c,"begin",function(){g.Gm(b,!0)});
c.play()},nfb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.NY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ha(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Gm(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.tm(l,"right",b.image_width+"px");g.gh(a.Ib(),l);a.C=new g.sp(function(){lfb(a,h,l)},500);
g.P(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){mfb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},mfb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Fm(b);a.j||(b.style.width=g.zm(f.width,!0),c.style.width=g.zm(f.width,!0));g.tm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.tm(d,"right","1px");a.D=!0;g.Gm(b,!0);a.G=new g.sp(function(){g.Ap(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},lfb=function(a,b,c){g.Cp(a.Ib(),"iv-branding-active");
a.K=new g.sp(function(){g.Gm(b,!1);a.j||(c.style.width=g.zm(0,!0))},250);
a.K.start();a.D=!1},ofb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.Y=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},pfb=function(a,b,c){v3.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.W=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.sp(function(){d.j.setAttribute("aria-hidden","true");g.Gm(d.C,!1);g.Gm(d.B,!0)},700,this);
g.P(this,this.G)},sfb=function(a,b,c){c.stopPropagation();
qfb(a);rfb(a,b);a.j.focus()},tfb=function(a){a.isCollapsed||a.Z||a.D||(g.Ap(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},qfb=function(a){a.G.stop();
a.isCollapsed&&(g.Dp(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Gm(a.B,!1),g.Gm(a.C,!0))},rfb=function(a,b){a.D||(a.D=g.Bi(function(){ufb(this);
tfb(this)},b,a))},ufb=function(a){a.D&&(g.Ma.clearTimeout(a.D),a.D=null)},vfb=function(a){this.J=a},afb=function(a,b,c){b&&(c?x3(a,b.map(function(d){return g.Ko(d,c)})):x3(a,b))},x3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.w(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.nv(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},wfb=function(a){g.gY.call(this,a);
var b=this;this.oa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new vfb(this.player);this.D=new g.aG(this);this.G=this.N=null;this.events=new g.aG(this);this.kh=this.W=this.j=null;this.qa=[];g.P(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.c5,this);this.subscribe("resize",this.cM,this);this.player.U().La.subscribe("vast_info_card_add",this.l1,this);g.P(this,this.events);this.Aa=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.S({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.P(this,this.B);g.SS(this.player,this.B.element,4);this.B.hide();this.C=new g.S({I:"div",Ka:["ytp-iv-video-content"]});g.P(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Aa);this.C.element.appendChild(a);this.Iv()&&this.load();var c=this.createElement({I:"style"});(g.Wg("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.jh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},xfb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Gm(a,!1);return a},yfb=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.Lx(a.B,b);g.Lx(a.C,b)},zfb=function(a,b,c){a.Z=!0;
a.G=g.Sr(b,c)},Afb=function(a,b){for(var c={},d=g.w(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Sa(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Afb(a,e))}return c},Efb=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.U().La.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.Hr(h)&&h.responseXML?h.responseXML:null)&&Bfb(a,h)}};
g.vt()&&(d.onFinish=Cfb(a,d.onFinish));d.postParams={ic_only:"1"};Dfb(d,c);a.Z=!0;g.Sr(b.Ta,d)}}},Dfb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.GJ&&(a.postParams.ic_coll=b.GJ);b.XO&&(a.postParams.ic_xml=b.XO);b.rN&&(a.postParams.ic_track=b.rN)},Ffb=function(a){var b=new g.S({I:"div"});
g.Gm(b.element,!1);var c=new Web(a.player,b.element,y3(a));g.P(c,b);b.Ha(a.B.element);c.fI();return c},Hfb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.oa=!0,Gfb(a,b),b.headerText&&a.kh&&(c=g.Px(b.headerText),a.kh.setAttribute("title",c))},y3=function(a){if(!a.W){var b=new peb(a);
g.P(a,b);var c=new g.Dk(a);g.P(a,c);a.W=new ofb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Pj)}return a.W},Bfb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.Ww();if(e){var f=g.Vw();f&&g.rr(g.px)(void 0,e,f,[g.Tw(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Afb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=f3(f.type,Ifb),p=f3(f.style,Jfb),q=Feb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=Leb;if(t==null)var u=null;else if(g.Ra(t)){l=[];for(var y=g.w(t),A=y.next();!A.done;A=y.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var G=f(t);u=G?[G]:[]}e=m&&n?new Meb(m,n,p,u,r):null}else e=null}catch(ea){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=xfb(f),M=null;switch(l.type){case "branding":if(f.player.U().Ld)break;f.B.element.appendChild(H);M=new w3(H,y3(f),l);break;case "promotion":g.SS(f.player,H,4),M=new pfb(H,y3(f),l)}M&&M.fI();if(f=M)g.P(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=Ffb(a),g.P(a,a.j));if(e.type==="card"){H=a.j;var N=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(N)switch(f=e.tracking||{},f={NZ:f.impression,click:f.click,close:f.close,l3:f.teaser_impression,mN:f.teaser_click},l=e.tracking_params||{},M=null,N){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,wj:f,Xp:l.card?g.Tw(l.card):null,gk:l.teaser?g.Tw(l.teaser):null,Gf:l.icon?g.Tw(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:h3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};q3(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,wj:f,
Xp:l.card?g.Tw(l.card):null,gk:l.teaser?g.Tw(l.teaser):null,Gf:l.icon?g.Tw(l.icon):null,vI:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:h3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};q3(H,c);break;case "productListing":e.signin_url&&(M=h3({target:"current",value:e.signin_url}));N=[];for(var X=e.offers||[],V=0;V<X.length;V++)N.push(new Seb(g.cg(X[V].merchant),
g.cg(X[V].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,wj:f,Xp:l.card?g.Tw(l.card):null,gk:l.teaser?g.Tw(l.teaser):null,Gf:l.icon?g.Tw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,SE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:h3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),tqa:M,sqa:e.signin_title?e.signin_title:void 0,rqa:e.signin_message?e.signin_message:void 0,offers:N,onClickCommand:null};q3(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,wj:f,Xp:l.card?g.Tw(l.card):
null,gk:l.teaser?g.Tw(l.teaser):null,Gf:l.icon?g.Tw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,SE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:h3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};q3(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,wj:f,Xp:l.card?g.Tw(l.card):null,gk:l.teaser?g.Tw(l.teaser):null,Gf:l.icon?g.Tw(l.icon):null,vI:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:h3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},q3(H,c)}}else Xeb(a.j,e);c=!0}}c&&
(R2(a.player),a.cM())},Gfb=function(a,b){var c=!1;
a.j||(a.j=Ffb(a),g.P(a,a.j));for(var d=g.w(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Yeb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.CR(f)||(c=a.j,d=b.headerText?g.Px(b.headerText):"",g.lh(c.Kb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.Tw(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.Tw(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Gf=b.icon.infoCardIconRenderer.trackingParams?g.Tw(b.icon.infoCardIconRenderer.trackingParams):null,a.cM());R2(a.player)}},Kfb=function(a,b,c,d,e){if(!a.player.U().Ld){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.vR)&&g.Q(b.navigationEndpoint,g.vR).browseId&&f.push(new Ieb("openUrl","click",new Geb("/channel/"+g.Q(b.navigationEndpoint,g.vR).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.wR)){d.channel_id=g.Q(b.subscribeButton,g.wR).channelId;var l;b=g.Q(b.subscribeButton,g.wR);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Px(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Px(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Px(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Px(b.subscriberCountWithSubscribeText)));var m,n=((m=g.Q((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.K1))==null?void 0:m.url)||"";l={subscribeText:g.Px(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.Px(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Meb(c,"branding","branding",f,d);l=xfb(a);a.B.element.appendChild(l);f=new w3(l,y3(a),f);f.fI();g.P(f,f);a.K[c]=f}},Cfb=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.Ia()||a.qa.push(g.lp.Zi(function(){b.apply(null,g.x(c))}))}},Lfb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.HS.prototype.GC=g.ba(35,function(a,b){var c=g.vY(this.yb());c&&c.GC(a,b)});
var T2={},U2=null;g.Za(W2,g.Fp);g.k=W2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;V2(this);this.startTime=a=g.Ya();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.SL();this.po("play");this.isPaused()&&this.po("resume");this.j=1;var b=g.Va(this);b in T2||(T2[b]=this);ieb();jeb(this,a);return!0};
g.k.stop=function(a){V2(this);this.j=0;a&&(this.progress=1);keb(this,this.progress);this.onStop();this.Ks()};
g.k.pause=function(){this.isPlaying()&&(V2(this),this.j=-1,this.po("pause"))};
g.k.xa=function(){this.j==0||this.stop(!1);this.po("destroy");W2.Tf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.pO=function(){this.po("animate")};
g.k.po=function(a){this.dispatchEvent(new leb(a,this))};
g.Za(leb,g.Nh);g.Za(X2,W2);X2.prototype.C=function(){};
X2.prototype.pO=function(){this.C();X2.Tf.pO.call(this)};
X2.prototype.Ks=function(){this.C();X2.Tf.Ks.call(this)};
X2.prototype.SL=function(){this.C();X2.Tf.SL.call(this)};
g.Za(meb,X2);meb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z(peb,g.O);g.k=peb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.Wa)(c,d||this.B);a=g.Ps(a,b,c);this.j.push(a);return a};
g.k.GG=function(a,b,c,d){c=(0,g.Wa)(c,d||this.B);a=geb(a,b,c);this.j.push(a);return a};
g.k.Lc=function(a){g.Qs(a);g.Xb(this.j,a)};
g.k.removeAll=function(){g.Qs(this.j);this.j.length=0};
g.k.xa=function(){this.removeAll();g.O.prototype.xa.call(this)};g.z(seb,g.gY);g.k=seb.prototype;g.k.load=function(){g.gY.prototype.load.call(this);if(!$2(this)){var a=g.cMa(this.player.getVideoData());a?(a=reb(a,teb(this)),a3(this,a,!1)):ueb(this)}};
g.k.unload=function(){a3(this,null);this.C&&(this.C.abort(),this.C=null);g.gY.prototype.unload.call(this)};
g.k.ji=function(a,b){return $2(this)?a==="loadCustomEndscreenRenderer"?(a=reb(b,"new"),a3(this,a),!0):null:null};
g.k.getOptions=function(){return $2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.kc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Mfb.length;f++){var h=Math.abs(b.width-Mfb[f]);if(e===-1||d>=h)e=f,d=h}d=Nfb[e];this.B&&g.tm(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Em(e.element,m,f);g.Am(e.element,n,p);g.Dp(e.element,Ofb);m>256||f>256?g.Ap(e.element,"ytp-ce-large-round"):m>96||f>96?g.Ap(e.element,"ytp-ce-medium-round"):g.Ap(e.element,"ytp-ce-small-round");g.Dp(e.element,Pfb);m=h.left+h.width/2;h=h.top+l/2;g.Ap(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Dp(e.element,Nfb);g.Ap(e.element,d);(e=g.Xg(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.tm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")e3(this,this.endscreen.impressionUrls),(a=g.Ww())&&this.endscreen.visualElement&&g.yx(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Ap(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Ap(b,"ytp-ce-shown");e3(this,c.impressionUrls);(b=g.Ww())&&g.yx(b,c.visualElement);this.player.U().N&&this.player.eb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.Cp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Cp(b,"ytp-ce-shown");this.player.U().N&&this.player.eb("endscreenelementhidden",a)}};
g.k.qda=function(a){var b=this;a.target===window&&(new g.sp(function(){for(var c=g.w(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Dp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Mfb=[346,426,470,506,570,640,853,1280,1920],Nfb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Pfb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Ofb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Heb={Mha:"current",rka:"new"};var Jeb={CLOSE:"close",wka:"openUrl",SUBSCRIBE:"subscribe"},Keb={vha:"click",CLOSE:"close",Oia:"hidden",lla:"rollOut",mla:"rollOver",yla:"shown"};Meb.prototype.Ge=function(){var a=Neb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var Jfb={Gga:"anchored",E4:"branding",CHANNEL:"channel",Lha:"cta",Ria:"highlightText",Eja:"label",PLAYLIST:"playlist",POPUP:"popup",Gla:"speech",SUBSCRIBE:"subscribe",Rla:"title",VIDEO:"video",Ama:"website"},Ifb={E4:"branding",iha:"card",Yha:"drawer",Qia:"highlight",Vja:"marker",Rka:"promotion",TEXT:"text",cna:"widget"};g.z(l3,g.O);g.k=l3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.BE(a,b,{id:c,namespace:"annotations_module"});d&&this.Ta.set(a,d);e&&this.Xa.set(a,e);this.context.J.qf([a],1)};
g.k.fI=function(){this.context.B.subscribe("resize",this.BJ,this)};
g.k.Ib=function(){return this.element};
g.k.KN=function(a,b,c,d,e,f){if(this.kb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.jh(this.Ib())};
g.k.BJ=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=g3(a);if(f){var h=Ueb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Jf||!1,n=g.xr(f||"");m&&n&&(n.v||n.list)?e.context.J.Gp(n.v,b,n.list,!1):g.pz(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);x3(this.context.logger,c,l,d);Teb(f)||(c=g.Ww(),d=b.itct,c&&d&&g.Bx(c,g.Tw(d)))}};
g.k.xa=function(){this.Ta.clear();this.Xa.clear();g.O.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.z(Web,l3);g.k=Web.prototype;g.k.Bu=function(){this.qa&&q3(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Fm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.BJ=function(){var a=this.isAvailable();g.Gm(this.Ib(),a);g.Ep(this.context.J.getRootNode(),g.S_.IV_DRAWER_ENABLED,a);R2(this.J)};
g.k.destroy=function(){this.J.GC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.Hv(this.oa);g.Ws(this.Oa);this.Ua&&this.Ua.dispose();this.G&&this.G.dispose();l3.prototype.destroy.call(this)};
g.k.nJ=function(){var a=this,b=g.Zg("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.b8,this);this.context.j.listen(this.B,"touchend",function(){a.Ca.start()});
this.context.j.listen(this.B,"scroll",this.A8,this);this.context.B.subscribe("onHideControls",function(){a.La=!0});
this.context.B.subscribe("onShowControls",function(){a.La=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.La=g.zp(a.J.getRootNode(),"ytp-autohide")});
this.oa.push(g.Gv("iv-button-shown",this.eaa,this));this.oa.push(g.Gv("iv-button-hidden",this.daa,this));cfb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Ub(this.cards,function(c){return a.Bf.startMs>c.Bf.startMs||a.Bf.startMs===c.Bf.startMs&&a.Bf.timestamp>=c.Bf.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.b8=function(){if(this.C){x3(this.context.logger,u3(this).wj.close);var a=g.Ww();a&&this.N&&g.Bx(a,this.N);p3(this)}};
g.k.A8=function(){g.Ep(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.eaa=function(){var a=g.Ww(),b=u3(this);b=b?b.Gf:this.Gf;a&&b&&g.zx(a,[b])};
g.k.daa=function(){var a=g.Ww(),b=u3(this);b=b?b.Gf:this.Gf;a&&b&&g.Ax(a,[b])};
g.k.b5=function(){var a=u3(this);x3(this.context.logger,a.wj.l3);var b=g.Ww();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.gk&&c.push(a.gk);a.Gf&&c.push(a.Gf);c.length>0&&g.zx(b,c)}else g.zx(b,[a.gk,a.Gf])};
g.k.haa=function(){var a=g.Ww(),b=u3(this);a&&b&&g.Ax(a,[b.gk])};
g.k.a5=function(a){var b=u3(this),c=g.Ww();this.j?a?(a=this.context.logger,x3(a,b.wj.mN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.gk&&g.Bx(c,b.gk)):(a=this.context.logger,x3(a,b.wj.mN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Gf&&g.Bx(c,b.Gf)):(a=this.context.logger,x3(a,b.wj.mN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Gf&&g.Bx(c,this.Gf))};g.z(v3,l3);v3.prototype.fI=function(){l3.prototype.fI.call(this);jfb(this)};
v3.prototype.show=function(){l3.prototype.show.call(this);var a=g.Ww(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.zx(a,[g.Tw(b.itct)])};
v3.prototype.hide=function(){l3.prototype.hide.call(this);var a=g.Ww(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Ax(a,[g.Tw(b.itct)])};g.z(w3,v3);
w3.prototype.Zy=function(){g.Ap(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Gm(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.Ge();c&&m3(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||nfb(this,
a)};
w3.prototype.show=function(){if(!this.isActive&&(v3.prototype.show.call(this),this.N||(this.Zy(),this.N=!0),g.Gm(this.Ib(),!0),this.isActive=!0,this.B)){try{kfb(this,this.B)}catch(a){}g.Ap(this.context.J.getRootNode(),"ytp-branding-shown")}};
w3.prototype.hide=function(){this.isActive&&(v3.prototype.hide.call(this),g.Gm(this.Ib(),!1),this.isActive=!1,g.Cp(this.context.J.getRootNode(),"ytp-branding-shown"))};
w3.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);v3.prototype.destroy.call(this)};g.z(pfb,v3);g.k=pfb.prototype;
g.k.Zy=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.Ge(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&m3(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Nf(f,g3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",va:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",va:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&m3(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.Ap(this.j,"iv-click-target");e&&m3(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",va:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.Ap(this.j,"iv-click-target"),e&&m3(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){sfb(a,5E3,q)});
c.appendChild(this.B);g.Gm(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.d$,this);this.context.j.listen(this.Ib(),"mouseout",this.c$,this);this.context.j.listen(this.Ib(),"touchend",function(q){sfb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.Y9:this.X9,this);c.appendChild(this.C);g.Bp(this.Ib(),d);h&&(g.gh(this.Ib(),h),n&&h.appendChild(n));g.gh(this.Ib(),this.N);g.gh(this.Ib(),c)};
g.k.show=function(){this.isActive||(v3.prototype.show.call(this),this.W||(this.Zy(),this.W=!0),g.Gm(this.Ib(),!0),g.Bi(function(){g.Cp(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,ufb(this),qfb(this),rfb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Ap(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.KN=function(a,b,c,d,e,f){return this.isCollapsed?!1:v3.prototype.KN.call(this,a,b,c,d,e,f)};
g.k.d$=function(a){this.Z=!0;sfb(this,500,a)};
g.k.c$=function(){this.Z=!1;tfb(this)};
g.k.X9=function(a){a.stopPropagation();this.hide()};
g.k.Y9=function(a){a.stopPropagation();ufb(this);this.isCollapsed=!0;g.Ap(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();v3.prototype.destroy.call(this)};g.z(wfb,g.gY);g.k=wfb.prototype;g.k.ji=function(a,b){if(!Lfb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.n1(b))&&Bfb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&($eb(this.j,b),R2(this.player)),!0}return null};
g.k.getOptions=function(){return Lfb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Iv=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.QR(b)||this.player.isMutedByEmbedsMutedAutoplay()?!1:c===1&&!b.e4||a.La.get(b.videoId)||g.DR(b)||g.ER(b)?!0:!1};
g.k.cM=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Em(this.C.element,a.width,a.height);g.Am(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Go();a=this.j;b=b.width;g.Ep(a.D,"iv-drawer-small",b<=426);g.Ep(a.D,"iv-drawer-big",b>=1280)}};
g.k.c5=function(a){yfb(this,a.state);g.U(a.state,2)&&(this.Dl()&&this.Up()&&this.player.getPresentingPlayerType()!==2&&this.HC(!1),this.GC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Hr(h)&&h.responseXML?h.responseXML:null)&&(Bfb(b,h),g.Ap(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.gY.prototype.load.call(this);yfb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.vt()&&(a=Cfb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().La.get(d);f&&Dfb(e,f);f=f&&(f.XO||f.GJ);if(!c.pw||f)c.Ta?zfb(this,c.Ta,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.CR(h))&&!b.oa&&Hfb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.SS(this.player,this.C.element,4);this.cM();(f=g.DR(c))&&Gfb(this,f);(f=g.ER(c))&&f.featuredChannel&&Kfb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.kh=g.Zg("ytp-cards-button",this.player.getRootNode());g.CR(c)&&Hfb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&zfb(this,b.Ta,a)};
g.k.unload=function(){this.player.kf("annotations_module");for(var a=g.w(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.W=null;this.j&&(this.j.destroy(),this.j=null,R2(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.oa=!1;this.K={};this.B.hide();g.gY.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.l1=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Efb(this):this.load())};
g.k.Dl=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.oa};
g.k.Up=function(){return!!this.j&&this.j.C};
g.k.HC=function(a,b,c){b=b===void 0?!1:b;this.Dl();this.j&&(a?c?o3(this.j,c,b):o3(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):p3(this.j))};
g.k.GC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().La.unsubscribe("vast_info_card_add",this.l1,this);g.Cp(this.player.getRootNode(),g.S_.IV_DRAWER_OPEN);for(var a=this.qa,b=g.lp,c=0,d=a.length;c<d;c++)b.Gj(a[c]);this.qa.length=0;g.gY.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.fY("annotations_module",wfb);g.fY("creatorendscreen",seb);})(_yt_player);
