(function(g){var window=this;'use strict';var N5=function(a,b){g.S.call(this,{I:"button",Ka:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],X:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",X:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",X:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",X:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",X:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.listen("click",this.onClick,this);this.updateValue("title",g.nS(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.lS(b.Ve(),this.element))},Blb=function(a){g.S.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.N=this.G=!1;this.player=a;this.T(a,"minimized",this.Bh);this.T(a,"onStateChange",this.dfa);this.T(a,"documentpictureinpicturechange",this.pba)},Clb=function(a,b){g.Ep(a.player.getRootNode(),"ytp-player-minimized",b);
a.player.L("web_cairo_modern_miniplayer")&&g.Ep(a.player.getRootNode(),"ytp-modern-miniplayer",b);a.player.L("web_cairo_modern_miniplayer_inset_progress_bar")&&g.Ep(a.player.getRootNode(),"ytp-miniplayer-alternate-ui",b)},Dlb=function(a){var b=a.player.ob().getPlayerSize().width,c=0,d=b;
if(a.player.L("web_cairo_modern_miniplayer")&&!a.N&&!a.player.L("web_cairo_modern_miniplayer_infobar")||a.player.L("web_cairo_modern_miniplayer_inset_progress_bar"))c=12,d=b-24;g.Y3a(a.progressBar,c,d,!1);g.AZ(a.progressBar)},Elb=function(a){g.gY.call(this,a);
this.B=new g.aG(this);this.j=new Blb(this.player);this.j.hide();g.SS(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.Ep(a.getRootNode(),"ytp-player-minimized",!0))};
g.z(N5,g.S);N5.prototype.onClick=function(){this.J.eb("onExpandMiniplayer")};g.z(Blb,g.S);g.k=Blb.prototype;
g.k.show=function(){this.j=new g.rp(this.v5,null,this);this.j.start();if(!this.G){this.tooltip=new g.j_(this.player,this);g.P(this,this.tooltip);g.SS(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.le=new g.JY(this.player);g.P(this,this.le);this.progressBar=new g.zZ(this.player,this);g.P(this,this.progressBar);g.SS(this.player,this.progressBar.element,4);this.player.L("web_cairo_modern_miniplayer_infobar")&&g.Ap(this.player.getRootNode(),"ytp-always-showing-infobar");this.B=new g.S({I:"div",
S:"ytp-miniplayer-scrim"});g.P(this,this.B);this.B.Ha(this.element);this.T(this.B.element,"click",this.X0);var a=new g.S({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.Ux()]});g.P(this,a);a.Ha(this.B.element);this.T(a.element,"click",this.yV);a=new N5(this.player,this);g.P(this,a);a.Ha(this.B.element);this.C=new g.S({I:"div",S:"ytp-miniplayer-controls"});g.P(this,this.C);this.C.Ha(this.B.element);this.player.L("web_cairo_modern_miniplayer")||this.T(this.C.element,
"click",this.X0);var b=new g.S({I:"div",S:"ytp-miniplayer-button-container"});g.P(this,b);b.Ha(this.C.element);a=new g.S({I:"div",S:"ytp-miniplayer-play-button-container"});g.P(this,a);a.Ha(this.C.element);var c=new g.S({I:"div",S:"ytp-miniplayer-button-container"});g.P(this,c);c.Ha(this.C.element);this.W=new g.uZ(this.player,this,!1);g.P(this,this.W);this.W.Ha(b.element);b=new g.tZ(this.player,this);g.P(this,b);b.Ha(a.element);this.nextButton=new g.uZ(this.player,this,!0);g.P(this,this.nextButton);
this.nextButton.Ha(c.element);this.K=this.player.L("web_cairo_modern_miniplayer")?new g.c_(this.player,this,0):new g.c_(this.player,this);g.P(this,this.K);this.K.Ha(this.B.element);this.D=new g.S({I:"div",S:"ytp-miniplayer-buttons"});g.P(this,this.D);g.SS(this.player,this.D.element,4);a=new g.S({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.Ux()]});g.P(this,a);a.Ha(this.D.element);this.T(a.element,"click",this.yV);a=new g.S({I:"button",Ka:["ytp-miniplayer-replay-button",
"ytp-button"],X:{"aria-label":"Close"},V:[g.$x()]});g.P(this,a);a.Ha(this.D.element);this.T(a.element,"click",this.vca);this.player.L("web_cairo_modern_miniplayer")&&(a=new N5(this.player,this),g.P(this,a),a.Ha(this.D.element));this.T(this.player,"presentingplayerstatechange",this.w5);this.T(this.player,"appresize",this.kc);this.T(this.player,"fullscreentoggled",this.kc);this.player.L("web_cairo_modern_miniplayer")&&this.T(this.player,"onPlaylistUpdate",this.JS);this.kc();this.G=!0}this.player.getPlayerState()!==
0&&g.S.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.S.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.S.prototype.xa.call(this)};
g.k.yV=function(){this.player.L("kevlar_watch_while_v2")||this.player.stopVideo();this.player.eb("onCloseMiniplayer")};
g.k.vca=function(){this.player.playVideo()};
g.k.X0=function(a){if(a.target===this.B.element||a.target===this.C.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.k.Bh=function(){Clb(this,this.player.isMinimized());this.player.L("web_cairo_modern_miniplayer")&&this.JS()};
g.k.pba=function(){Clb(this,this.player.hj());this.player.L("web_cairo_modern_miniplayer")&&this.JS();g.Ep(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.hj())};
g.k.Fg=function(){this.progressBar.Rc();this.K.Rc()};
g.k.v5=function(){this.Fg();this.j&&this.j.start()};
g.k.w5=function(a){g.U(a.state,32)&&this.tooltip.hide()};
g.k.JS=function(){this.N=(this.player.isMinimized()||this.player.hj())&&!!this.player.getPlaylist();g.Ep(this.player.getRootNode(),"ytp-has-playlist-data",this.N);Dlb(this)};
g.k.kc=function(){Dlb(this)};
g.k.dfa=function(a){this.player.isMinimized()&&(a===0?this.hide():this.show())};
g.k.Ve=function(){return this.tooltip};
g.k.Py=function(a,b,c,d,e){var f=0,h=0,l=0,m=g.Fm(a);d=b&&(g.zp(b,"ytp-prev-button")||g.zp(b,"ytp-next-button"));if(b){c=g.zp(b,"ytp-play-button");var n=g.zp(b,"ytp-miniplayer-expand-watch-page-button");d?f=l=12:c?(b=g.Dm(b,this.element),l=b.x,f=b.y-12):n&&(l=g.zp(b,"ytp-miniplayer-button-top-left"),f=g.Dm(b,this.element),b=g.Fm(b),l?(l=8,f=f.y+40):(l=f.x-m.width+b.width,f=f.y-20))}else l=c-m.width/2,h=25+(e||0);b=this.player.ob().getPlayerSize();e=f+(e||0);m=g.og(l,0,b.width-m.width-12);e?(a.style.top=
e+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=h+"px");a.style.left=m+"px";this.player.L("web_cairo_modern_miniplayer")&&(h=g.zp(a,"ytp-preview"),a.style.visibility=d&&h&&b.height<225?"hidden":"")};g.z(Elb,g.gY);g.k=Elb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.Ep(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.gY.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.In=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.fY("miniplayer",Elb);})(_yt_player);
